### ISSUE TITLE
Use YAML

### ISSUE THREAD

**Issue by owainlewis** [owainlewis/daenerys#1]
Do this with YAML as well

``` yaml

---
url: https://bbc.co.uk
method: GET
headers:
  Content-Type: application/json
```
